branch-defaults:
  main:
    environment: Udagramfull-env
    group_suffix: null
deploy:
  artifact: ./src/Archive.zip
global:
  application_name: udagramfull
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
